
# a way to reduce my typing load:-)

all: doit

doit:
	./sf-ips.py

test:
	./sf-ips.py test

newtest:
	./m100.sh
	./sf-ips.py test

clean:
	rm -f ips.*.csv hours.*.csv regips.*.csv irregips.*.csv fewrecs.csv.bup
